Fix Xcode 26.4 compilation error
The error was:

> TypingOperationQueue.swift:96:38: error: sending 'pendingRequest' risks causing data races
> await pendingRequest.performOperation()
>       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
>
> note: sending main actor-isolated 'pendingRequest' to nonisolated instance method 'performOperation()' risks causing data races between nonisolated and main actor-isolated uses

A Swift 6.3 issue, it would seem. I guess that perhaps the nested
Request type no longer inherits the main actor isolation of its
containing type?

Resolves ably/ably-cocoa#2202 (reporter opened issue there).